export const GETTING_TASKS = 'GETTING_TASKS';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const GETTING_TASKS_START = 'GETTING_TASKS_START';
export const GETTING_TASKS_SUCCESS = 'GETTING_TASKS_SUCCESS';
export const GETTING_TASKS_ERROR = 'GETTING_TASKS_ERROR';