export const GETTING_TASKS_START = 'GETTING_TASKS_START';
export const GETTING_TASKS_SUCCESS = 'GETTING_TASKS_SUCCESS';
export const GETTING_TASKS_ERROR = 'GETTING_TASKS_ERROR';
export const SHOW_CREATE_TASK = 'SHOW_CREATE_TASK';
export const HIDDEN_CREATE_TASK = 'HIDDEN_CREATE_TASK';
